In [1]:
import numpy as np

In [5]:
arr = np.arange(64).reshape(8, -1)

In [4]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [6]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [7]:
arr[0:8:4,0:8:4]

array([[ 0,  4],
       [32, 36]])